[package]
name = "logger-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lunatic = "0.10.0-alpha.1"
tracing = "0.1"
# tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
vtable = "0.1"
