name: Security Audit

on:
  push:
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'

  pull_request:
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'

jobs:
  cargo_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
